services:

  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgres/data

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  css:
    build: 
      context: .
      target: development
    tty: true
    command: "bundle exec rails tailwindcss:watch"
    volumes:
      - .:/usr/src/cat-a-log
      - bundle:/usr/local/bundle

  web:
    build: 
      context: .
      target: development
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/usr/src/cat-a-log
      - bundle:/usr/local/bundle
      - playwright_cache:/root/.cache/ms-playwright
    ports:
      - 3000:3000
    environment:
      - DISPLAY=:0
      - RAILS_MAX_THREADS=5
      - RAILS_ENV=development
      - RACK_ENV=development
      - REDIS_PERSISTENCE_URL=redis://redis:6379
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - db
      - redis
      - css

volumes:
  postgres_data:
  redis_data:
  bundle:
  playwright_cache:
